options:
  port: 5353
  address: 0.0.0.0

routes:

 - regex: ([a-z]+)\.example\.com\.$
   action: googlehttps

 - glob: "*.reddit.com"
   action:
      name: zone
      zone:
        - www.reddit.com. 60 IN A 1.2.3.4